# Define the pins
tank_contol:
  ros__parameters:
    left_motor_forward: 20
    left_motor_backward: 21 
    right_motor_forward: 19
    right_motor_backward: 26
    left_motor_pwm: 16
    right_motor_pwm: 13

    timeout: 2.0
    rate: 50.0
    max_speed: 2.0
    max_pwm: 255
    # The distance between two wheel(track)
    wheel_base: 1 #0.15
    
    imu_frame_id: imu_link
    imu_bus: 3
    accel_offset_x: -0.540
    accel_offset_y: -0.570
    accel_offset_z: 0.290
    gyro_offset_x: 0.393
    gyro_offset_y: -0.142
    gyro_offset_z: 0.690
    imu_rate: 10.0